// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCi5pqJ8DTxwOLvV-lSuxkmBgmJ6L6-VV0",
    authDomain: "teamsoftnoz-cbbiz.firebaseapp.com",
    projectId: "teamsoftnoz-cbbiz",
    storageBucket: "teamsoftnoz-cbbiz.appspot.com",
    messagingSenderId: "1025356878029",
    appId: "1:1025356878029:web:369f887955d69787e59984",
    measurementId: "G-1BMCJVBDL4",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-fLFCwMpVDQ3e9wOhhQkjUCM7p72oEes',
    appId: '1:1025356878029:android:e01a9432cacfdf25e59984',
    messagingSenderId: '1025356878029',
    projectId: 'teamsoftnoz-cbbiz',
    storageBucket: 'teamsoftnoz-cbbiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4-SKPv7kb8ONJfYaoMmov8h2yrE9N9w0',
    appId: '1:116414671430:ios:d9edca60b3d6d7ed35b847',
    messagingSenderId: '116414671430',
    projectId: 'cbbankbiz',
    storageBucket: 'cbwaybiz.appspot.com',
    iosClientId:
        '176432592591-mqf3bmf038pq03l60tv375bsoab2h826.apps.googleusercontent.com',
    iosBundleId: 'cbbank.vn.cbwaybiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOP9M9bvOXFtigzZhOxQMX-aYZtpn0sko',
    appId: '1:176432592591:ios:f3c61981b44098d3bca9ba',
    messagingSenderId: '176432592591',
    projectId: 'cbbankbiz',
    storageBucket: 'cbbankbiz.appspot.com',
    iosClientId:
        '176432592591-mqf3bmf038pq03l60tv375bsoab2h826.apps.googleusercontent.com',
    iosBundleId: 'cbbank.vn.cbwaybiz',
  );
}
