// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeHSE13fJgCc_RBwxi76cxNzmsb3_xxaw',
    appId: '1:176432592591:web:d85d6ddec85e71c2bca9ba',
    messagingSenderId: '176432592591',
    projectId: 'cbbankbiz',
    authDomain: 'cbbankbiz.firebaseapp.com',
    storageBucket: 'cbbankbiz.appspot.com',
    measurementId: 'G-1V9H7LDZSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4-SKPv7kb8ONJfYaoMmov8h2yrE9N9w0',
    appId: '1:116414671430:android:180f2d3571f137c435b847',
    messagingSenderId: '116414671430',
    projectId: 'cbbankbiz',
    storageBucket: 'cbbankbiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4-SKPv7kb8ONJfYaoMmov8h2yrE9N9w0',
    appId: '1:116414671430:ios:d9edca60b3d6d7ed35b847',
    messagingSenderId: '116414671430',
    projectId: 'cbbankbiz',
    storageBucket: 'cbwaybiz.appspot.com',
    iosClientId:
        '176432592591-mqf3bmf038pq03l60tv375bsoab2h826.apps.googleusercontent.com',
    iosBundleId: 'cbbank.vn.cbwaybiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOP9M9bvOXFtigzZhOxQMX-aYZtpn0sko',
    appId: '1:176432592591:ios:f3c61981b44098d3bca9ba',
    messagingSenderId: '176432592591',
    projectId: 'cbbankbiz',
    storageBucket: 'cbbankbiz.appspot.com',
    iosClientId:
        '176432592591-mqf3bmf038pq03l60tv375bsoab2h826.apps.googleusercontent.com',
    iosBundleId: 'cbbank.vn.cbwaybiz',
  );
}
